### ISSUE TITLE
Failure to find org.elasticsearch.client:x-pack-transport:jar:5.6.2 

### ISSUE THREAD

**Issue by SuperDubbo** [elastic/found-shield-example#14]
Failure to find org.elasticsearch.client:x-pack-transport:jar:5.6.2

**Comment by igor-kupczynski** [comment]
Hey, sorry for not responding earlier. We've updated the repo a couple of times since this issue and we use a different ES version now. 

I'm going to close the issue as outdated, feel free to raise a new one if you still see problems fetching the dependencies.
